config/routes.rb
Rails.application.routes.draw do
  resources :baseball_cards
  root "baseball_cards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/baseball_card.rb
class BaseballCard < ApplicationRecord
  TEAMS = [
    {town: 'Chicago', team: 'White Sox'},
    {town: 'Cleveland', team: 'Guardians'},
    {town: 'Detroit', team: 'Tigers'},
    {town: 'Kansas City', team: 'Royals'},
    {town: 'Minnesota', team: 'Twins'},
    {town: 'Baltimore', team: 'Orioles'},
    {town: 'Boston', team: 'Red Sox'},
    {town: 'New York', team: 'Yankees'},
    {town: 'Tampa Bay', team: 'Rays'},
    {town: 'Toronto', team: 'Blue Jays'},
    {town: 'Houston', team: 'Astros'},
    {town: 'Los Angeles', team: 'Angels'},
    {town: 'Oakland', team: 'Athletics'},
    {town: 'Seattle', team: 'Mariners'},
    {town: 'Texas', team: 'Rangers'},
    {town: 'Chicago', team: 'Cubs'},
    {town: 'Cincinnati', team: 'Reds'},
    {town: 'Milwaukee', team: 'Brewers'},
    {town: 'Pittsburgh', team: 'Pirates'},
    {town: 'St. Louis', team: 'Cardinals'},
    {town: 'Atlanta', team: 'Braves'},
    {town: 'Miami', team: 'Marlins'},
    {town: 'New York', team: 'Mets'},
    {town: 'Philadelphia', team: 'Phillies'},
    {town: 'Washington', team: 'Nationals'},
    {town: 'Arizona', team: 'Diamondbacks'},
    {town: 'Colorado', team: 'Rockies'},
    {town: 'Los Angeles', team: 'Dodgers'},
    {town: 'San Diego', team: 'Padres'},
    {town: 'San Francisco', team: 'Giants'},
  ]
  
  POSITIONS = [
    'Pitcher',
    'Catcher',
    '1st Base',
    '2nd Base',
    '3rd Base',
    'Shortstop',
    'Left Field',
    'Center Field',
    'Right Field',
  ]
  
  validates :name, presence: true
  validates :image_url, presence: true
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/baseball_cards_controller.rb
class BaseballCardsController < ApplicationController
  before_action :set_baseball_card, only: %i[ show edit update destroy ]

  # GET /baseball_cards or /baseball_cards.json
  def index
    @baseball_cards = BaseballCard.all
  end

  # GET /baseball_cards/1 or /baseball_cards/1.json
  def show
  end

  # GET /baseball_cards/new
  def new
    @baseball_card = BaseballCard.new
  end

  # GET /baseball_cards/1/edit
  def edit
  end

  # POST /baseball_cards or /baseball_cards.json
  def create
    @baseball_card = BaseballCard.new(baseball_card_params)

    respond_to do |format|
      if @baseball_card.save
        format.html { redirect_to baseball_card_url(@baseball_card), notice: "Baseball card was successfully created." }
        format.json { render :show, status: :created, location: @baseball_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @baseball_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baseball_cards/1 or /baseball_cards/1.json
  def update
    respond_to do |format|
      if @baseball_card.update(baseball_card_params)
        format.html { redirect_to baseball_card_url(@baseball_card), notice: "Baseball card was successfully updated." }
        format.json { render :show, status: :ok, location: @baseball_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @baseball_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baseball_cards/1 or /baseball_cards/1.json
  def destroy
    @baseball_card.destroy

    respond_to do |format|
      format.html { redirect_to baseball_cards_url, notice: "Baseball card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baseball_card
      @baseball_card = BaseballCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baseball_card_params
      params.require(:baseball_card).permit(:name, :team, :position, :image_url)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: %i[ show edit update destroy ]

  # GET /welcomes or /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1 or /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes or /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1 or /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to welcome_url(@welcome), notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1 or /welcomes/1.json
  def destroy
    @welcome.destroy

    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.fetch(:welcome, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baseball_cards_helper.rb
module BaseballCardsHelper
  def team_options_for_select(selected=nil)
    teams = BaseballCard::TEAMS.reduce({}) do |hash, town_team_hash|
      hash.merge(town_team_hash.values.join(' ') => town_team_hash[:team])
    end
    options_for_select(teams, selected)
  end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/baseball_cards/_form.html.erb
<%= form_with(model: baseball_card) do |form| %>
  <% if baseball_card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(baseball_card.errors.count, "error") %> prohibited this baseball_card from being saved:</h2>

      <ul>
        <% baseball_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= button_tag 'Another Player Image', type: '', id: :update_card_player_image %>
  </div>

  <div>
    <%= form.label :team, style: "display: block" %>
    <%= form.select :team, team_options_for_select(@baseball_card&.team) %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.select :position, BaseballCard::POSITIONS %>
  </div>
  
  <div>
    <%= form.hidden_field :image_url %>
    <%= form.submit %>
  </div>
<% end %>

<br />

<%= render @baseball_card %>

app/views/baseball_cards/edit.html.erb
<h1>Editing baseball card</h1>

<div>
  <%= link_to "Show this baseball card", @baseball_card %> |
  <%= link_to "Back to baseball cards", baseball_cards_path %>
</div>

<br>

<%= render "form", baseball_card: @baseball_card %>

app/views/baseball_cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Baseball cards</h1>

<%= link_to "New baseball card", new_baseball_card_path %>

<div id="baseball_cards">
  <% @baseball_cards.each do |baseball_card| %>
    <%= link_to baseball_card do %>
      <%= render baseball_card, baseball_card: baseball_card %>
    <% end %>
  <% end %>
</div>

app/views/baseball_cards/new.html.erb
<h1>New baseball card</h1>

<div>
  <%= link_to "Back to baseball cards", baseball_cards_path %>
</div>

<br>

<%= render "form", baseball_card: @baseball_card %>

app/views/baseball_cards/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <%= link_to "Edit this baseball card", edit_baseball_card_path(@baseball_card) %> |
  <%= link_to "Back to baseball cards", baseball_cards_path %>

  <%= button_to "Destroy this baseball card", @baseball_card, method: :delete %>
</div>

<%= render @baseball_card %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Baseball Cards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome) do |form| %>
  <% if welcome.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
        <% welcome.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/_welcome.html.erb
<div id="<%= dom_id welcome %>">
</div>

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render "form", welcome: @welcome %>

<br>

<div>
  <%= link_to "Show this welcome", @welcome %> |
  <%= link_to "Back to welcomes", welcomes_path %>
</div>

app/views/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render "form", welcome: @welcome %>

<br>

<div>
  <%= link_to "Back to welcomes", welcomes_path %>
</div>

app/views/welcomes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @welcome %>

<div>
  <%= link_to "Edit this welcome", edit_welcome_path(@welcome) %> |
  <%= link_to "Back to welcomes", welcomes_path %>

  <%= button_to "Destroy this welcome", @welcome, method: :delete %>
</div>